# Generated by Django 6.0.2 on 2026-02-07 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='executable_file',
            field=models.FileField(blank=True, null=True, upload_to='product_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['exe'])]),
        ),
    ]
